---
# tasks file for common
#

- name: Install common apt packages
  apt:
    state: present
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
  environment:
    DEBIAN_FRONTEND: noninteractive
  with_items: "{{ common_apt_packages }}"

